[PIM-57] 반응형 보드페이지 구현
gachon-sw-academy-2023/Prello pull request #16
Opened 2023-01-19 01:27 UTC by Seyiul

## 반응형 보드페이지 구현 

### 지라 티켓 번호
PIM-57

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 리팩토링
- [x] UI 구현 및 변경

### 구현 내용
<img width="542" alt="스크린샷 2023-01-19 오전 10 23 58" src="https://user-images.githubusercontent.com/63714074/213333969-b4e1b487-0a66-488e-a046-37294aaf53b4.png">
<img width="542" alt="스크린샷 2023-01-19 오전 10 23 48" src="https://user-images.githubusercontent.com/63714074/213333977-e162f3f1-0938-4fed-afeb-ce75f4732f2e.png">

- 보드 페이지 ➡️ 반응형으로 구현
- 모바일 헤더 및 사이드바 컴포넌트 생성
- 기존의 버그 수정
    - 리스트의 순서를 바꿀때, `  + add another list  `의 위치까지 바뀌던 오류 수정

### 리뷰 포인트
화면 크기에 따라서 헤더와 사이드바 영역이 사진과 같이 변경되는 지 같이 확인해주세요

### TODO

2023-01-19 05:19 UTC, CHOSIYEON approved these changes
확인했습니다~! 아주 잘 동작하네유 😆😆😆

2023-01-19 05:27 UTC, SeonDahye requested changes
화면 하단의 배경색이 아닌 빈공간이 있는데 확인부탁드려요!

2023-01-19 05:43 UTC, Seyiul commented
> 화면을 줄였을 때, 가로 스크롤이 생겨버리네용 확인부탁드려요~!

수정 완료했습니다~ 다시 확인해주세요 !

2023-01-19 05:43 UTC, Seyiul commented
> 화면 하단의 배경색이 아닌 빈공간이 있는데 확인부탁드려요!

수정 완료했습니다~ 다시 확인해주세요 !

2023-01-25 02:15 UTC, CHOSIYEON approved these changes
수고하셨습니다~!

2023-01-25 02:15 UTC, SeonDahye approved these changes
PIM-61 브랜치에서 하단 공간 문제 수정했어요 ! 💡💡

2023-01-25 02:16 UTC, merged