[PIM-59] 반응형 회원가입 페이지 구현
gachon-sw-academy-2023/Prello pull request #17
Opened 2023-01-19 02:11 UTC by Seyiul

## 반응형 회원가입 페이지 구현 

### 지라 티켓 번호
PIM-59

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 리팩토링
- [x] UI 구현 및 변경

### 구현 내용
<img width="839" alt="스크린샷 2023-01-19 오전 11 07 55" src="https://user-images.githubusercontent.com/63714074/213339031-0e62da96-c023-485c-b7f7-7bdd00933329.png">
<img width="1582" alt="스크린샷 2023-01-19 오전 11 07 49" src="https://user-images.githubusercontent.com/63714074/213339034-c5f71d2d-8967-4c86-8876-1ed530931872.png">
반응형 회원가입 페이지 구현

### 리뷰 포인트
화면 크기에 따라서 회원가입 페이지가 잘 변동되는 지 확인해주세요

### TODO
- [ ] 모바일 헤더 컴포넌트가 머지된 후에 헤더를 추가할 예정입니다.

2023-01-19 05:22 UTC, CHOSIYEON approved these changes
확인했습니다~! 아주 잘 동작하네유 😆😆😆

2023-01-19 05:37 UTC, SeonDahye requested changes
아주 잘 동작하네요! 👍👍
그런데 화면 줄어들 때 **로그인** 버튼은 있어야할 것 같아요..!

2023-01-25 02:18 UTC, SeonDahye approved these changes
헤더에 로그인 버튼을 넣는것도 좋은 방법이네요 !! 👍👍

2023-01-25 02:21 UTC, CHOSIYEON approved these changes
수고하셨습니다 !!

2023-01-25 02:22 UTC, merged