[PIM-60] 반응형 로그인 화면 구현
gachon-sw-academy-2023/Prello pull request #18
Opened 2023-01-19 02:23 UTC by Seyiul

## 반응형 로그인 화면 구현 

### 지라 티켓 번호
PIM-60

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 리팩토링
- [x] UI 구현 및 변경

### 구현 내용
<img width="691" alt="스크린샷 2023-01-19 오전 11 21 29" src="https://user-images.githubusercontent.com/63714074/213340487-911263c2-b2f0-4878-adc7-eaf5ba90d2c0.png">
<img width="1582" alt="스크린샷 2023-01-19 오전 11 21 23" src="https://user-images.githubusercontent.com/63714074/213340508-2306415f-a8ef-427d-b425-934520771ed2.png">

반응형 로그인 화면 구현

### 리뷰 포인트
화면 크기에 따라서 로그인 페이지가 잘 변동되는 지 확인해주세요

### TODO

- [ ]  모바일 헤더 컴포넌트가 머지된 후에 헤더를 추가할 예정입니다.

2023-01-19 05:29 UTC, CHOSIYEON requested changes
src/pages/authorization/login/index.tsx 파일에서 

  useEffect(() => {
    if (login && emailValidation && pwdValidation) {
      navigate(routes.WORKSPACEDEFAULT);
    }
  });

useEffect에 의존값을 넣어야할 것 같아요! 빠져있네용 확인 부탁드려요~! 👍

2023-01-19 05:41 UTC, SeonDahye requested changes
고생하셨어요 🙌🙌
회원가입 페이지와 마찬가지로 화면이 줄어들면 회원가입버튼이 사라지네요 ㅠㅠ

2023-01-25 02:20 UTC, SeonDahye approved these changes
회원가입 화면과 마찬가지로 헤더 추가해주세요 ~~!

2023-01-25 02:26 UTC, Seyiul commented
> src/pages/authorization/login/index.tsx 파일에서
> 
> useEffect(() => { if (login && emailValidation && pwdValidation) { navigate(routes.WORKSPACEDEFAULT); } });
> 
> useEffect에 의존값을 넣어야할 것 같아요! 빠져있네용 확인 부탁드려요~! 👍

수정완료하였습니다! 다시확인해주세용

2023-01-25 02:28 UTC, CHOSIYEON approved these changes
수정사항 확인했습니다~ 수고하셨습니당 😆😆😆

2023-01-25 02:28 UTC, merged