[PIM-88] 아이템 상세 페이지 기능 구현
gachon-sw-academy-2023/Prello pull request #43
Opened 2023-02-09 02:35 UTC by Seyiul

## 아이템 상세 페이지 기능 구현  

### 지라 티켓 번호
PIM-88

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 리팩토링
- [x] UI 구현 및 변경

### 구현 내용
<img width="1582" alt="스크린샷 2023-02-09 오전 11 21 37" src="https://user-images.githubusercontent.com/63714074/217702442-b47b2d95-7014-4258-959e-3e08b845c8e2.png">

아이템 상세 페이지 기능 구현 
- 아이템 설명∙팀원∙날짜 변경 가능
- 아이템 삭제 구현

### 리뷰 포인트
오류 있는지 함께 확인해주세요

### TODO
오류 핸들링 추가할게여

2023-02-09 02:47 UTC, CHOSIYEON commented on src/pages/board/Card/Card.tsx
> +              <Item key={item.id} itemId={item.id} fetchItems={fetchItems}>
컴포넌트한테 넘겨줄 때, 이벤트 헨들러로 넘겨야 한다는 멘토님의 피드백이 있었어요,,,😭😭😭
같이 수정해 봅시다 ~!

2023-02-09 02:49 UTC, CHOSIYEON commented on src/pages/board/Item/Item.tsx
> +      {isOpen && <Detail setOpen={handleModal} itemId={itemId} />}
이 부분도 setOpen으로 함수 넘기는게 아니라 이벤트 헨들러로 넘겨줘야 할 것 같아요!

2023-02-09 02:50 UTC, CHOSIYEON requested changes
아이템에서 멤버를 먼저 추가하고, 댓글을 작성할 때 입력이 되지 않는 버그가 있어욤 
수정 부탁드려요 ~~~

2023-02-09 04:44 UTC, SeonDahye approved these changes
**설명 추가하기** 제외하고 잘 작동됩니다! 수고하셨어요~~

2023-02-09 04:44 UTC, SeonDahye commented on src/mocks/Board/itemHandlers.ts
> +  }),
리턴할 때 status가 200인 경우와 아닌 경우로 나누면 에러 처리 시 좋을 것 같네요!! 👍👍

2023-02-10 01:15 UTC, CHOSIYEON approved these changes
수고하셨습니다~! 😍😍😍

2023-02-10 01:17 UTC, merged